# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
imports:
    - { resource: 'legacy_aliases.yml'}

parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    
    # _instanceof:
    #     Twig_ExtensionInterface:
    #         tags: ['twig.extension']

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        

    AppBundle\Service\MarkdownTransformer:
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']

    
        
        